shell commit

diff --git a/08_simple_shell_0.4/exit_status b/08_simple_shell_0.4/exit_status
--- a/08_simple_shell_0.4/exit_status
+++ b/08_simple_shell_0.4/exit_status
@@ -1,9 +1,10 @@
 #!/bin/bash
 #
-# check that the PATH is checked in the right order
+# Checks exit command
 
-command="ls"
+command="exit"
 tmp_file="checker_tmp_file_$RANDOM"
+save_file=`echo $BASH_SOURCE | sed -e 's/\.\///g' -e 's/\//#/g'`
 
 # clean up
 stop_shell
@@ -11,21 +12,18 @@ rm -f $tmp_file
 
 # create a pseudo random file
 touch $tmp_file
-# empty PATH
-OLDPATH="$PATH"
-PATH=":$PATH"
 # send commands
-$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
-
-# put PATH back
-PATH="$OLDPATH"
+$ECHO "$command" | $SHELL; echo $? > $OUTPUTFILE 2> $ERROROUTPUTFILE &
 
 # wait a little bit
 $SLEEP $SLEEPSECONDS
 
+# copy saved output for debugging
+cat $OUTPUTFILE > "$SAVEOUTPUTDIR/$save_file"
+
 # check the result
 res=`$CAT "$OUTPUTFILE"`
-if [ "$res" == "cisfun" ]; then
+if [ "$res" == "0" ]; then
     print_ok
 else
     print_ko
